### ISSUE TITLE
virgil command not found. Downloaded virgil-cli on ubuntu 16.04 using the script . However when i try to generate private key the terminal prompts virgil command not found. 

### ISSUE THREAD

**Issue by alishaagupta** [VirgilSecurity/virgil-cli#11]

**Comment by nau11713** [comment]
Hello @alishaagupta. 
Please confirm that you correctly installed the CLI (this guide provides more details https://developer.virgilsecurity.com/docs/sdk-and-tools/virgil-cli/configure). It can be confirmed using the command: `virgil -h`.
Also when you specify the output file, be sure that you have permissions to write the file into the necessary directory.
