### ISSUE TITLE
Can't use CLI public key to create new app

### ISSUE THREAD

**Issue by cbetta** [VirgilSecurity/virgil-cli#8]
I've installed the CLI on my mac, generated a private and public key (with password), but when I try to upload this to the dashboard I get the following error.

<img width="526" alt="screen shot 2016-11-01 at 20 53 35" src="https://cloud.githubusercontent.com/assets/7718/19907105/6255e4d8-a075-11e6-9fe8-664477ecd312.png">

Did I create the key incorrectly?

**Comment by vadimavdeev** [comment]
Apparently `.key` file extension is reserved on Mac. As a workaround I'd suggest you change the key file extension to `.txt`

**Comment by cbetta** [comment]
Ah awesome, might be worth documenting? 

FYI I tested this and it worked

**Comment by vadimavdeev** [comment]
Great! I think it's better to remove file extensions from example commands, so it would be like 
`virgil keygen -o privatekey`

**Comment by cbetta** [comment]
@vadimavdeev indeed.
